project:
  type: website
  output-dir: ../docs   # para que el sitio quede en /docs (útil para GH Pages)

website:
  title: "RTWMA"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: notebooks/03_wma/01_GWF_DFC_WMA_Yeso/1_GWF_DFC_WMA_Imp.ipynb
        text: Análisis 1
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - section: "Notebooks"
        contents:
          - notebooks/03_wma/01_GWF_DFC_WMA_Yeso/1_GWF_DFC_WMA_Imp.ipynb
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    embed-resources: false