# File generated by Flopy version 3.9.3 on 06/22/2026 at 16:59:49.
BEGIN options
  XT3D_OFF
END options

BEGIN griddata
  alh
    CONSTANT       1.00000000
  ath1
    CONSTANT       1.00000000
END griddata

